namespace eCLAdmin.Models.Report
{
    public class CoachingLogQn
    {
        public string ModuleId { get; set; }
        public string ModuleName { get; set; }
        public string CoachingID { get; set; }
        public string LogName { get; set; }
        public string QualityNowBatchID { get; set; }
        public string QualityNowBatchStatus { get; set; }
        public string Status { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string Site { get; set; }
        public string SupervisorEmployeeID { get; set; }
        public string SupervisorName { get; set; }
        public string ManagerEmployeeID { get; set; }
        public string ManagerName { get; set; }
        public string CurrentSupervisorEmployeeID { get; set; }
        public string CurrentSupervisorName { get; set; }
        public string CurrentManagerEmployeeID { get; set; }
        public string CurrentManagerName { get; set; }
        public string ReviewSupervisorEmployeeID { get; set; }
        public string ReviewSupervisorName { get; set; }
        public string ReviewManagerEmployeeID { get; set; }
        public string ReviewManagerName { get; set; }
        public string StrengthandOpportunities { get; set; }
        public string EvaluationSummary { get; set; }
        public string CoachingNotes { get; set; }
        public string EventDate { get; set; }
        public string CoachingDate { get; set; }
        public string SubmittedDate { get; set; }
        public string CoachingSource { get; set; }
        public string SubCoachingSource { get; set; }
        public string CoachingReason { get; set; }
        public string SubCoachingReason { get; set; }
        public string Value { get; set; }
        public string SubmitterID { get; set; }
        public string SubmitterName { get; set; }
        public string SupervisorReviewedDate { get; set; }
        public string ManagerReviewedManualDate { get; set; }
        public string ManagerReviewedAutoDate { get; set; }
        public string ManagerNotes { get; set; }
        public string EmployeeReviewedDate { get; set; }
        public string EmployeeComments { get; set; }
        public string FollowupRequired { get; set; }
        public string FollowupDate { get; set; }
        public string FollowupCoachingDate { get; set; }
        public string FollowupCoachingNotes { get; set; }
        public string SupervisorFollowupAutoDate { get; set; }
        public string CSRFollowupAcknowledged { get; set; }
        public string CSRFollowupAutoDate { get; set; }
        public string CSRFollowupComments { get; set; }
        public string FollowupSupervisorID { get; set; }
        public string SupervisorFollowupReviewAutoDate { get; set; }
        public string SupervisorFollowupReviewCoachingNotes { get; set; }
        public string FollowupReviewMonitoredLogs { get; set; }
        public string FollowupReviewSupervisorID { get; set; }
        public string Program { get; set; }
        public string Channel { get; set; }
        public string VerintID { get; set; }
        public string ActivityID { get; set; }
        public string DCN { get; set; }
        public string VerintFormName { get; set; }
        public string CoachingMonitor { get; set; }
        public string EvaluationStatus { get; set; }
        public string ReasonForContact { get; set; }
        public string ReasonForContactComments { get; set; }
        public string BusinessProcess { get; set; }
        public string BusinessProcessReason { get; set; }
        public string BusinessProcessComment { get; set; }
        public string InfoAccuracy { get; set; }
        public string InfoAccuracyReason { get; set; }
        public string InfoAccuracyComment { get; set; }
        public string PrivacyDisclaimers { get; set; }
        public string PrivacyDisclaimersReason { get; set; }
        public string PrivacyDisclaimersComment { get; set; }
        public string IssueResolution { get; set; }
        public string IssueResolutionComment { get; set; }
        public string BusinessCorrespondence { get; set; }
        public string BusinessCorrespondenceComment { get; set; }
        public string CallEfficiency { get; set; }
        public string CallEfficiencyComment { get; set; }
        public string ChatEfficiency { get; set; }
        public string ChatEfficiencyComment { get; set; }
        public string ActiveListening { get; set; }
        public string ActiveListeningComment { get; set; }
        public string IssueDiagnosis { get; set; }
        public string IssueDiagnosisComment { get; set; }
        public string PersonalityFlexing { get; set; }
        public string PersonalityFlexingComment { get; set; }
        public string ProfessionalCommunication { get; set; }
        public string ProfessionalCommunicationComment { get; set; }
        public string CustomerTempStart { get; set; }
        public string CustomerTempStartComment { get; set; }
        public string CustomerTempEnd { get; set; }
        public string CustomerTempEndComment { get; set; }
    }
}