IF EXISTS (
    SELECT table_name FROM INFORMATION_SCHEMA.TABLES 
	WHERE TABLE_NAME = N'LoadTest_User')
BEGIN
    DROP TABLE ec.LoadTest_User;
END;
GO

CREATE TABLE ec.LoadTest_User
(
    ID INT IDENTITY PRIMARY KEY NOT NULL,
	EmpID NVARCHAR(20) NOT NULL
);
GO
