'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MySurveyLogDetailView

    '''<summary>
    '''PageLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PageLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PageValueLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PageValueLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FormIDLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormIDLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FormIDValueLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormIDValueLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''StatusLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''StatusValueLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusValueLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DateSubmittedLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DateSubmittedLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DataSubmittedValueLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DataSubmittedValueLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TypeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TypeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TypeValueLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TypeValueLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CoachingDatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CoachingDatePanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''CoachingDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CoachingDateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CoachingDateValueLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CoachingDateValueLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EventDatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EventDatePanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''EventDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EventDateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EventDateValueLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EventDateValueLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SourceLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SourceLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SourceValueLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SourceValueLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SiteLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SiteLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SiteValueLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SiteValueLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VerintPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VerintPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''VerintIDLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VerintIDLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VerintIDValueLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VerintIDValueLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ScoreCardNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScoreCardNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ScoreCardNameValueLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScoreCardNameValueLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''AvokeIDPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AvokeIDPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''AvokeIDLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AvokeIDLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''AvokeIDValueLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AvokeIDValueLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''NgdActivityIDPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NgdActivityIDPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''NgdActivityIDLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NgdActivityIDLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''NgdActivityIDValueLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NgdActivityIDValueLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UniversalCallIDPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UniversalCallIDPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''UniversalCallIDLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UniversalCallIDLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UniversalCallIDValueLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UniversalCallIDValueLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EmployeeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmployeeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EmployeeValueLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmployeeValueLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SupervisorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SupervisorLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SupervisorValueLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SupervisorValueLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ManagerLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ManagerLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ManagerValueLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ManagerValueLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SubmitterLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitterLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SubmitterValueLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitterValueLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''InstructionLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InstructionLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CoachingReasonLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CoachingReasonLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CoachingReasonGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CoachingReasonGridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''BehaviorDetailsPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BehaviorDetailsPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''BehaviorDetailsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BehaviorDetailsLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BehaviorDetailsTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BehaviorDetailsTable As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''BehaviorDetailsValueLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BehaviorDetailsValueLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CustomerServiceEscalationLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomerServiceEscalationLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''NonCustomerServiceEscalationPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NonCustomerServiceEscalationPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ManagementNotesPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ManagementNotesPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ManagementNotesLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ManagementNotesLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ManagementNotesTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ManagementNotesTable As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''ManagementNotesValueLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ManagementNotesValueLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''NonCustomerServiceEscalationLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NonCustomerServiceEscalationLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CoachingNotesPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CoachingNotesPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''CoachingNotesLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CoachingNotesLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CoachingNotesTabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CoachingNotesTabel As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''CoachingNotesValueLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CoachingNotesValueLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EmployeeReviewInformationLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmployeeReviewInformationLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EmployeeNameValueLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmployeeNameValueLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EmployeeReviewedDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmployeeReviewedDateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EmployeeReviewedDateValueLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmployeeReviewedDateValueLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SupervisorReviewInformationPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SupervisorReviewInformationPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''SupervisorReviewInformationLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SupervisorReviewInformationLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SupervisorNameValueLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SupervisorNameValueLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SupervisorReviewedDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SupervisorReviewedDateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SupervisorReviewedDateValueLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SupervisorReviewedDateValueLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EmployeeCommentsFeedbackPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmployeeCommentsFeedbackPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''EmployeeCommentsFeedbackLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmployeeCommentsFeedbackLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EmployeeCommentsFeedbackTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmployeeCommentsFeedbackTable As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''EmployeeCommentsFeedbackValueLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmployeeCommentsFeedbackValueLabel As Global.System.Web.UI.WebControls.Label
End Class
