'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MySurvey

    '''<summary>
    '''MyScriptManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MyScriptManager As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''UpdateProgress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgress1 As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''MySurveyUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MySurveyUpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''SuccessMsgLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SuccessMsgLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''AccessDeniedMsgLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AccessDeniedMsgLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''QuestionsPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuestionsPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''InstructionLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InstructionLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TitleLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TitleLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MySurveyLogLinkButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MySurveyLogLinkButton As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''FailMsgLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FailMsgLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Question1Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Question1Label As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Question1RadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Question1RadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Question1TextBoxLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Question1TextBoxLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Question1TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Question1TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Question2Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Question2Label As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Question2RadioBUttonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Question2RadioBUttonList As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Question2TextBoxLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Question2TextBoxLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Question2TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Question2TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Question3Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Question3Label As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Question3RadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Question3RadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Question3TextBoxLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Question3TextBoxLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Question3TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Question3TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Question4Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Question4Label As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Question4RadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Question4RadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Question4TextBoxLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Question4TextBoxLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Question4TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Question4TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Question5Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Question5Label As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Question5RadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Question5RadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Question5TextBoxLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Question5TextBoxLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Question5TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Question5TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HotTopicPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HotTopicPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Question6Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Question6Label As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Question6RadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Question6RadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Question6TextBoxLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Question6TextBoxLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Question6TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Question6TextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CommentTextBoxLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CommentTextBoxLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CommentTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CommentTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button
End Class
